### ISSUE TITLE
Corretto Java and Floating Point Correction, with Compatibility.

### ISSUE THREAD

**Issue by PowerUser1234** [corretto/corretto-18#17]
Dear Volker and Corretto,

This email is in regards to [https://github.com/corretto/corretto-18/issues/15](https://github.com/corretto/corretto-18/issues/15), which you have closed.

I/we are not in a position to just leave this particular subject where last left,
and we don't want the discussion or apprehension of this subject to remain closed and let by.

As we tried to describe on the beginning of our thread at [https://github.com/corretto/corretto-18/issues/15](https://github.com/corretto/corretto-18/issues/15) ,

Java floating point denormal and pronormal values, from arithmetic and StrictMath function calls, in terms
of range accuracy, don't correspond to decimal or binary mathematics.  Because they are not one or the other,
they don't correspond to anything.  IEEE 754 also, for these reasons, is incomplete, and trying to justify Java's present
state due to IEEE 754 is a _non sequitar_, as is similar thinking in relation to Corretto, at least right now.

-If just to start, how could correcting Java's **default** floating point behaviour possibly break compatibility?  **What on earth
could correcting the present, strange, erroneous and inconsistent behaviour of Java floating point as it is now,
possibly break compatibility with?** We can't really see or think of one example, certainly one that is most appropriate for Java,
and not a lower level language, which would more appropriately be wrapped to Java.  Forgive our naïveté, but are there really any such real coherent examples, at all, most pertinent to the Java and Corretto space, **needing** floating point errors, the infamous denormal and pronormal values ?!?!  Enhancements in the domain of SSE and similar now mean that compromising
range accuracy for speed doesn't need to happen any more.

-Still, the former matter is not the main thrust of our request.  Our request submission to Coretto still is for the sake of the
implementation and release of a Coretto Java **patch** to itself.  A patch can be included or omitted, installed
or not, still **allowing compatibility**.  But even with the inclusion of a patch, it would have to be possible that a "switch"  option relevant to floating point arithmetic or StrictMath source code sites or encapsulations, in the runtime **can** be included, to 
enable a changed floating point arithmetic or StrictMath **to continue to work with the previous one, in the very
same codespace, and even to interact with one another.**

Changes to Java floating point arithmetic and StrictMath, and any other closely bound classes or interfaces, 
can even be implemented at a finest grain level by a patch if desired, **even without altering how Java compiles**.  Annotations can be invented and applied which change the floating point arithmetic or StrictMath behaviour attenuation at runtime, for variables, objects, data, classes, or interfaces, all the key points of operation.  Annotations which the runtime can automatically react to, if they do occur, such that no annotation processor needs be submitted or specified by the Java coder, for such.

We, the body of Java Programmers, can't allow for this matter to pass, because we in fact are beginning to NEED corrected OpenJDK floating point arithmetic, and an equivalent corrected StrictMath, because of the 2D graphics and 3D visual graphics work we are now planning.  The present workarounds are too slow, and waste too much memory, amoung their other caveats.  We need continuous range accuracy from the facilities of the earlier types, _float and double_.  As will a larger number of programmers or companies out there, who haven't necessarily come forward, or persisted.  Formal requests made as part of the original Java Community Process have been blithely shut down and ignored with no technical and meaningful explanations,  reasoning on the issue point itself.  Which leads us to Coretto, and its patching options.

Since Coretto has announced that it has become a part of the Java Community Process, we were hoping that this kind of appeal, made here, to Corretto directly, would gain more traction, then trying to deal through former channels which have just shut this request down, providing no further amenability.  Because of its membership in the JCP, we thought that Corretto would be more interested in considering the needs or desires of the users and and end developers to an enlarged extent.

**Can those involved at Corretto seriously consider a floating point arithmetic/StrictMath, decimal mathematics,
total range accuracy patch for the Coretto JDK and JRE, implemented in one of the manners suggested here, 
for all platforms offered by Coretto, for its stable versions, and subsequent ones, into the future?**

The only thing any of us might further ask is what James Gosling himself thinks could and should be done here, now that he is part of Amazon Web Services and is associated with Corretto OpenJDK Java, himself?

**Comment by simonis** [comment]
Hi @PowerUser1234 ,

I'm sorry to disappoint you, but without any content-wise judgement of your request, I still can only refer you for such kind of requests to the OpenJDK project and its mailing lists [which you're already familiar with](https://mail.openjdk.java.net/pipermail/core-libs-dev/2022-March/087023.html).

Thanks one more time and best regards,
Volker
