### ISSUE TITLE
Corretto Java, Floating Point Correction?

### ISSUE THREAD

**Issue by PowerUser1234** [corretto/corretto-18#18]
Dear Corretto,

is it possible for someone else, other than Volker Simonis, to re-read and respond to my messages?

I have tried to post at

[https://github.com/corretto/corretto-18/issues/15](https://github.com/corretto/corretto-18/issues/15), and again at

[https://github.com/corretto/corretto-18/issues/17](https://github.com/corretto/corretto-18/issues/17)

in attempts to contect either Amazon Web Services or someone more actively involved in the Corretto Java project.

-Part of our problem is that there exists no totally free live internet chat that I can use to address either 
AWS or Corretto, also given that where I live it is (UTC + 9:30), which can mean that I am day/night 
opposite to people to other people in different places in the world.  I also can't submit a formal support
request and get a ticket number on basic, free support, it does seem.  Trying to contact and access
people involved in Corretto is therefore much harder, particularly if I trying to form an appeal involving one path
of thinking involved in Java, Corretto.

If there is a free live internet chat to AWS to Corretto, could someone please kindly reply to me with the URL here, please?

I/we need to appeal the decision made so far in the Issues area of GitHub for Corretto Java, that what we have posed about Corretto floating point can't be done because it is too incompatible, doesn't perfectly match IEEE 754, doesn't match the upstream Oracle OpenJDK and Oracle SE, or risks creating some split in the user base, either for OpenJDK or Corretto.

**We have tried to submit that such a change can be seen as compatible as a default change, and/or as a mutual change without altering how the language compiles, being a change in the runtime.  IEEE 754 isn't consistent or complete as a standard involving computing in range limited base 10 rational decimal numbers to begin with, but there are alternatives already available that do cohere, for hardware and software, that are available as source code for free, and are just as rapid as previous operations.  Floating Point denormals and pronormals don't appear to be any reliant feature, for the level of computing that Java does, and therefore are really a bug, no matter how characterised, or wherefrom, formally or otherwise.  However, a mutual mode would eliminate any kind of problem there at any rate.  Mutual compatibility means that possibilities get added to the Java base, not removed.  It can be the case that changing the Java default alone will also be compatible, if there is no specific, necessary, requirement basis to utilise floating point arithmetic and StrictMath function call denormals or pronormal values at any place or point.**

Can all my requests here on GitHub be handed on to someone else more deeply involved in Corretto, or can I be replied to with an email address, or a public internet free online chat service that I can use to address either AWS or Corretto in a more personal manner? **We wish to engage Corretto further, and don't simply want to be easily screened out.**  For us, this whole matter of floating point correction in Java is pretty well mission critical, combined with the fact that it can be seen as a total improvement, with no real ultimate caveats, since Corretto floating point improvement could incorporate the current and present way of doing things at the same time, if that was best.

Can someone else please address us here, and submit my questioning further, and respond as I have described, here, kindly, please?

**Comment by davecurrie** [comment]
I am the manager of the Corretto team at AWS and can confirm that Volker is a senior member of the team and speaks on our behalf.

I'd like to re-iterate Volker's point that this is not the place to discuss a change in how OpenJDK works. The correct place is in the appropriate OpenJDK mailing list, which I think you've already written to. As an open source project which is run in public, specification changes need to be discussed and agreed upon with the community. Corretto will ship any changes that happen in OpenJDK.

**Comment by PowerUser1234** [comment]
We begin by sharing the view that the ideal for changes in Java would be from the JCP and the original OpenJDK, downstream from there.  I and others have attempted to discuss floating point matters on core-libs-dev, and the bugs list as well.  What we are finding is that phenomena and deductions involved, the nature of the floating point error problem, positive implications for our requests for all involved with OpenJDK, alongside total mutual compatability, are simply getting immediately disregarded.  Yet the problem of the FP error state remain, and their consequences for people and ourselves does too. We have so far found that the Java Community Process is shutting our request down too early, and are creating a circumstantial brick wall .  

IEEE 754 seems to be some greater issue, which is a less rational state of affairs than the coherence to machine use, which is binary, and the coherence to decimal use, which is for us humans.  Some strange confusion in between, particularly with optimal, distinct implementation solutions in sight and freely available, is disadvantageous and creates inaccuracy and use problems, which should just be repaired at that point. Present workarounds possess a number of their own, further, disadvantages.

We have approached Corretto because of your reputation for creating patches to Java, alongside the compatability view to Java floating point correction that we have been submitting.  It becomes the difficult case for us and others in industry that if these corrections need to happen at any rate, and that JCP access points don't begin by responding more duly, then we should turn to a more flexible Java vendor elsewhere, such as yourselves.  

Withstanding agreement or disagreement on what we have proposed, floating point arithmetic and StrictMath changes as described at

[https://github.com/corretto/corretto-18/issues/15](https://github.com/corretto/corretto-18/issues/15) and [https://github.com/corretto/corretto-18/issues/17](https://github.com/corretto/corretto-18/issues/17) 

and in a known but older paper, at

[https://people.eecs.berkeley.edu/~wkahan/JAVAhurt.pdf](https://people.eecs.berkeley.edu/~wkahan/JAVAhurt.pdf)

alongside other similar, like-minded papers found at the bottom of the web page, at

[https://en.wikipedia.org/wiki/Floating-point_arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic)

repairing Corretto Java floating point possesses no disadvantages, and import key advantages.  We would be more than excited if either the default were altered, a mutual mode were implemented, or a patch developed and released, which can be either installed or left uninstalled.

Can Corretto please re-entertain this matter, as an opprtunity for a patch to enhance matters and repair bug problems in its distribution of its JDK and JRE?

**Comment by PowerUser1234** [comment]
Dear Corretto,

from what we have gathered, both ourselves and more widely, IEEE 754 has a blind spot in it.  An incompletion where either right or wrong can creep in.  This is towards the right hand side of float or double arithmetic and StrictMath method calls, 
where you have a straddling value for the last decimal place, that at that point is a confusion between the decimal and the binary; the decimal, which the human sees, and the binary, which is converterted to and away from, that the computer needs to perform operations on.

Since binary is for computers, and decimal is for humans, the most important root fact anyway, dealing with both of them means that you should deal with them one at a time, or convert them, entirely, one to the other.  This is exactly what Java floating point does not do. It deliberately confuses the two, at the wrong time, with denormals and pronormals, leading to what should be seen as 'floating point errors'.

The thing with a patch is that it is not the main stream, the primary product.  People have the specific option to include one or not.  Who could want or need a denormal or pronormal value, exactedly?  Any speed difference between accurate or innacurate is negligible because of SSE and similar anyway.  Why should all ubiquity Java Developers have no broader choice about how they react about an incomplete, therefore incorrect and flawed standard, and implementation? Present workarounds are only that, workarounds, and with float and double range are slower and larger than needs be.  A patch can leave the writing or reading or exchange of float and double between Java code spaces exactly the same, providing complete choice between two Java floating point operation modes.

Most importantly, what should happen about floating point error correction should Oracle, OpenJDK, JCP et al, the ideal points for improvement on FP errors, never listen, and persist in leaving these errors and program operations problem intact?  Surely it would be better for a downstream vendor to offer a patch for the problem, which is lower risk and apart from the mainstream, than this error problem remain ongoing and neglected in place, forever.

When the Java switch statement was enhanced, so that programmers could immediately switch via a String, and could also coelesce switch options using the -> operator, there was no split in Java because of an incompatability.  The fact that people had cause to learn something different and new about switch was no problem either.  The two compatability options only 
improved the circumstances for everyone.

If these are the needs and the circumstances, should Corretto at least consider a special Floating Point patch for Corretto Java, despites?
