### ISSUE TITLE
Make Corretto 18 available on Docker Hub

### ISSUE THREAD

**Issue by Harmelodic** [corretto/corretto-18#19]
### Is your feature request related to a problem?

The Corretto documentation details that a Corretto 18 docker image is available on Docker Hub:
https://docs.aws.amazon.com/corretto/latest/corretto-18-ug/docker-install.html

But, the image is not available:
https://hub.docker.com/_/amazoncorretto

### Describe a solution you would like

An amazoncorretto:18 image (with other images with associated tags) be available for use.

### Describe alternatives you have considered

Building my own, using the amazoncorretto download links:
https://docs.aws.amazon.com/corretto/latest/corretto-18-ug/downloads-list.html

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this. We're working on it right now in [corretto-docker#95](https://github.com/corretto/corretto-docker/pull/95), and will update the dockerhub images soon.

**Comment by Harmelodic** [comment]
Ah! Amazing, I didn't even realise there was a designated corretto docker repo.

Since you have the https://github.com/corretto/corretto-docker/issues/94 issue, then I'll close this issue and keep things clean.
