### ISSUE TITLE
Java Floating Point, the Nature of Errors, and the Present Context.

### ISSUE THREAD

**Issue by PowerUser1234** [corretto/corretto-18#25]
IEEE 754 and the path from it that is not correct.  Using the present workarounds is too slow and memory wasting as well.
The head of the problem is a logic error in base 10, denary.  Therfore Java Floating Point Errors should, must be corrected in place.
754 needs to be completed in terms of all floating phenomenon, certainly pertaining to representation limits and range end limits.
However, that is not inside the scope of this Bug Post.

In terms of the nature of a patch, differing away from the main object of the software artifact, concerns about compatability or risks from differing from the mainstream can be easily dismissed (look at what happened when the switch statement changed, since the analogy is between the switch change an a FP patch are pretty parallel). Corretto stands to make real gains for itself by implementing a floating point correction patch, which might change things even further for Floating Point, either under the Corretto umbrella, or further.

If indeed Oracle won't respond or begin to listen, that pretty well locks floating point correction out of SE and OpenJDK for the rest of us, and the all of us, a teh the broader ubiquity, community and business active acceptence. That isn't ultimately an acceptable option for many. The only ubiquity option is if another OpenJDK related vendor were prepared to accomplish floating point correction in one of a few different possible ways, in default or dual mode compatability manner.

If not, the root of the Java floating point error will remain the logic error that it is, addressed only by a stop gap measure, which is a hack with a set of object disadvantages, reducing the quality, speed and efficiency of Java maybe forever.

**Comment by simonis** [comment]
Constantly and monotonically reiterating the same question over and over won't change the answer (believe me, I have experience with this, I'm a father of three :)

If you think that Java is not the right program language for you please feel free to choose another language or to create your own, superior programming environment.

Corretto, like OpenJDK, is an open source project which you can easily fork and adapt to your own needs at any time.

[1] https://mail.openjdk.java.net/pipermail/core-libs-dev/2022-April/088782.html
[2] http://mail.openjdk.java.net/pipermail/core-libs-dev/2018-March/051952.html
