### ISSUE TITLE
Information about Corretto 18.0.2

### ISSUE THREAD

**Issue by rccha** [corretto/corretto-18#41]
We identified a potential issue with systems using Amazon Corretto 18.0.2 (July release). This issue could cause failures within C2 compilation of sun.security.ssl.SSLEngineInputRecord::decodeInputRecord.This issue is tracked upstream JBS - [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260). Since 18 is not an LTS release it was decided 18.0.2.1 update is much less critical than having the LTS updates containing the latest security updates be stable. Hence there is not going to be any fix release for this issue.

**Comment by benty-amzn** [comment]
Customers on Corretto 18 should move to Corretto 19 when it becomes available or to an LTS release
